export const FASTDATASETS_CONFIG_SCHEMA = [
  {
    param_key: 'input_files',
    en_name: 'Input Files',
    zh_name: '输入文件路径列表',
    data_type: 'array',
    default_value: [],
    description: '支持PDF、DOCX、TXT、MD格式的文件路径数组',
    required: true,
    group_key: 'FastDatasetsConfig',
    value_as_cmd: false,
    is_quick: false,
    is_estimator: false,
  },
  {
    param_key: 'output_dir',
    en_name: 'Output Directory',
    zh_name: '输出目录',
    data_type: 'string',
    default_value: '/workspace/user-data/datasets',
    description: '生成数据集的输出目录（固定值）',
    required: false,
    group_key: 'FastDatasetsConfig',
    value_as_cmd: false,
    is_quick: false,
    is_estimator: false,
    readonly: true,
  },
  {
    param_key: 'chunk_min_len',
    en_name: 'Min Chunk Length',
    zh_name: '最小分块长度',
    data_type: 'int',
    default_value: 200,
    description: '文本分块的最小字符数',
    required: false,
    group_key: 'FastDatasetsConfig',
    value_as_cmd: false,
    number_range: {
      min: 50,
      max: 10000,
      steps: 1,
    },
    number_render_type: 'slider',
    is_quick: false,
    is_estimator: false,
  },
  {
    param_key: 'chunk_max_len',
    en_name: 'Max Chunk Length',
    zh_name: '最大分块长度',
    data_type: 'int',
    default_value: 1000,
    description: '文本分块的最大字符数',
    required: false,
    group_key: 'FastDatasetsConfig',
    value_as_cmd: false,
    number_range: {
      min: 500,
      max: 20000,
      steps: 1,
    },
    number_render_type: 'slider',
    is_quick: false,
    is_estimator: false,
  },
  {
    param_key: 'questions_per_chunk',
    en_name: 'Questions Per Chunk',
    zh_name: '每块问题数',
    data_type: 'int',
    default_value: 2,
    description: '每个文本块生成的问题数量',
    required: false,
    group_key: 'FastDatasetsConfig',
    value_as_cmd: false,
    number_range: {
      min: 1,
      max: 10,
      steps: 1,
    },
    number_render_type: 'slider',
    is_quick: false,
    is_estimator: false,
  },
  {
    param_key: 'output_formats',
    en_name: 'Output Formats',
    zh_name: '输出格式',
    data_type: 'array',
    default_value: ['alpaca', 'sharegpt'],
    description: '生成数据集的格式（可多选）',
    required: false,
    group_key: 'FastDatasetsConfig',
    value_as_cmd: false,
    enum_options: [
      {
        name: 'alpaca',
        value: 'alpaca',
      },
      {
        name: 'sharegpt',
        value: 'sharegpt',
      },
    ],
    is_quick: false,
    is_estimator: false,
  },
  {
    param_key: 'enable_cot',
    en_name: 'Enable CoT',
    zh_name: '启用思维链',
    data_type: 'boolean',
    default_value: true,
    description: '是否启用Chain-of-Thought模式',
    required: false,
    group_key: 'FastDatasetsConfig',
    value_as_cmd: false,
    is_quick: false,
    is_estimator: false,
  },
  {
    param_key: 'llm_concurrency',
    en_name: 'LLM Concurrency',
    zh_name: 'LLM并发数',
    data_type: 'int',
    default_value: 3,
    description: 'LLM API并发请求数',
    required: false,
    group_key: 'FastDatasetsConfig',
    value_as_cmd: false,
    number_range: {
      min: 1,
      max: 50,
      steps: 1,
    },
    number_render_type: 'slider',
    is_quick: false,
    is_estimator: false,
  },
  {
    param_key: 'file_concurrency',
    en_name: 'File Concurrency',
    zh_name: '文件并发数',
    data_type: 'int',
    default_value: 2,
    description: '文件处理并发数',
    required: false,
    group_key: 'FastDatasetsConfig',
    value_as_cmd: false,
    number_range: {
      min: 1,
      max: 20,
      steps: 1,
    },
    number_render_type: 'slider',
    is_quick: false,
    is_estimator: false,
  },
  {
    param_key: 'api_key',
    en_name: 'API Key',
    zh_name: 'API密钥',
    data_type: 'string',
    default_value: '',
    description: 'LLM API密钥',
    required: true,
    group_key: 'FastDatasetsConfig',
    value_as_cmd: false,
    is_quick: false,
    is_estimator: false,
  },
  {
    param_key: 'base_url',
    en_name: 'Base URL',
    zh_name: 'API基础地址',
    data_type: 'string',
    default_value: '',
    description: 'LLM API的基础URL',
    required: true,
    group_key: 'FastDatasetsConfig',
    value_as_cmd: false,
    is_quick: false,
    is_estimator: false,
  },
  {
    param_key: 'model_name',
    en_name: 'Model Name',
    zh_name: '模型名称',
    data_type: 'string',
    default_value: '',
    description: '使用的LLM模型名称',
    required: true,
    group_key: 'FastDatasetsConfig',
    value_as_cmd: false,
    is_quick: false,
    is_estimator: false,
  },
] as const;
