export const PREDICT_TASK_ID = {
  param_key: 'taskId',
  en_name: '',
  zh_name: '微调模型',
  data_type: 'enum',
  default_value: '',
  description: '',
  required: true,
  value_as_cmd: false,
  is_quick: false,
  is_estimator: false,
};

export const PREDICT_TASK_BASE_MODEL = {
  param_key: 'taskBaseModel',
  en_name: '',
  zh_name: '基模型',
  data_type: 'string',
  default_value: '',
  description: '',
  required: false,
  value_as_cmd: false,
  is_quick: false,
  is_estimator: false,
  readonly: true,
};

export const PREDICT_BASIC_CONFIG_SCHEMA = [
  {
    param_key: 'per_device_eval_batch_size',
    en_name: '',
    zh_name: '单GPU批处理大小',
    data_type: 'int',
    default_value: 2,
    description: '每个进程（即每张 GPU）上处理的样本个数',
    required: false,
    group_key: 'PredictConfig',
    value_as_cmd: false,
    number_range: {
      min: 1,
      max: 1024,
      steps: 1,
    },
    number_render_type: 'slider',
    is_quick: false,
    is_estimator: true,
  },
  {
    param_key: 'cutoff_len',
    en_name: 'Cutoff Length',
    zh_name: '截断长度',
    data_type: 'int',
    default_value: 1024,
    description: '输入的最大 token 数，超过该长度会被截断',
    required: false,
    group_key: 'PredictConfig',
    value_as_cmd: false,
    number_render_type: 'slider',
    number_range: {
      min: 4,
      max: 131072,
      steps: 1,
    },
    is_quick: false,
    is_estimator: true,
  },
  {
    param_key: 'max_samples',
    en_name: 'Max Sample Size',
    zh_name: '最大样本数',
    data_type: 'int',
    default_value: 100000,
    description: '每个数据集的最大样本数：设置后，每个数据集的样本数将被截断至指定的 max_samples',
    required: false,
    group_key: 'PredictConfig',
    value_as_cmd: false,
    is_quick: false,
    is_estimator: true,
  },
  {
    param_key: 'seed',
    en_name: 'Random Seed',
    zh_name: '随机种子',
    data_type: 'int',
    default_value: 42,
    description: '用于数据加载器的随机种子',
    required: false,
    group_key: 'PredictConfig',
    value_as_cmd: false,
    is_quick: false,
    is_estimator: false,
  },
  {
    param_key: 'max_new_tokens',
    en_name: 'Maximum new tokens',
    zh_name: '最大生成长度',
    data_type: 'int',
    default_value: 512,
    description: '生成文本的最大长度。设置 max_new_tokens 会覆盖 max_length',
    required: false,
    group_key: 'PredictConfig',
    number_range: {
      min: 8,
      max: 4096,
      steps: 1,
    },
    number_render_type: 'slider',
    is_quick: false,
    is_estimator: true,
  },
  {
    param_key: 'top_p',
    en_name: 'top_p',
    zh_name: 'Top_p',
    data_type: 'float',
    default_value: 0.7,
    description:
      '用于控制生成时候选 token 集合大小的参数。例如：top_p = 0.7 意味着模型会先选择概率最高的若干个 token 直到其累积概率之和大于 0.7，然后在这些 token 组成的集合中进行采样。',
    required: false,
    group_key: 'PredictConfig',
    number_range: {
      min: 0.01,
      max: 1,
      steps: 0.01,
    },
    number_render_type: 'slider',
    is_quick: false,
    is_estimator: false,
  },
  {
    param_key: 'temperature',
    en_name: 'Temperature',
    zh_name: '温度系数',
    data_type: 'float',
    default_value: 0.95,
    description:
      '用于调整生成文本的随机性。temperature 越高，生成的文本越随机；temperature 越低，生成的文本越确定。',
    required: false,
    group_key: 'PredictConfig',
    number_range: {
      min: 0.01,
      max: 1.5,
      steps: 0.01,
    },
    number_render_type: 'slider',
    value_as_cmd: false,
    is_quick: false,
    is_estimator: false,
  },
  {
    param_key: 'save_predictions',
    en_name: 'Save predictions',
    zh_name: '保存预测结果',
    data_type: 'boolean',
    default_value: true,
    description: '保存模型评估预测结果',
    required: false,
    group_key: 'PredictConfig',
    value_as_cmd: false,
    is_quick: false,
    is_estimator: false,
  },
  // {
  //   param_key: 'finetuning_type',
  //   en_name: '',
  //   zh_name: '微调方法',
  //   data_type: 'enum',
  //   enum_options: [
  //     {
  //       name: 'lora',
  //       value: 'lora',
  //     },
  //     {
  //       name: 'freeze',
  //       value: 'freeze',
  //     },
  //     {
  //       name: 'full',
  //       value: 'full',
  //     },
  //   ],
  //   default_value: 'lora',
  //   description: '微调方法',
  //   required: false,
  //   group_key: 'PredictConfig',
  //   value_as_cmd: false,
  //   is_quick: true,
  //   is_estimator: true,
  // },
  // {
  //   param_key: 'checkpoint_path',
  //   en_name: '检查点路径',
  //   zh_name: 'checkpoint_path',
  //   data_type: 'string',
  //   default_value: '',
  //   description: '检查点路径',
  //   required: false,
  //   group_key: 'PredictConfig',
  //   value_as_cmd: false,
  //   is_quick: true,
  //   is_estimator: false,
  // },

  // {
  //   param_key: 'n_shot',
  //   en_name: 'Training Example Data',
  //   zh_name: '训练示例数量',
  //   data_type: 'int',
  //   default_value: 5,
  //   description: 'few-shot 的示例数量',
  //   required: false,
  //   group_key: 'PredictConfig',
  //   value_as_cmd: false,
  //   is_quick: true,
  //   is_estimator: false,
  // },

  // {
  //   param_key: 'quantization_config',
  //   en_name: 'QLoRA',
  //   zh_name: '量化',
  //   data_type: 'boolean',
  //   default_value: false,
  //   description: '量化',
  //   required: false,
  //   group_key: 'PredictConfig',
  //   value_as_cmd: false,
  //   is_quick: false,
  //   is_estimator: false,
  //   readonly: true,
  // },
  // {
  //   param_key: 'quantization_bit',
  //   en_name: 'Quantization Bit(QLoRA)',
  //   zh_name: '量化等级',
  //   data_type: 'enum',
  //   default_value: 'none',
  //   description: '指定在量化过程中使用的位数，通常是4位、8位等',
  //   enum_options: [
  //     {
  //       name: 'none',
  //       value: 'none',
  //     },
  //     {
  //       name: '4',
  //       value: '4',
  //     },
  //     {
  //       name: '8',
  //       value: '8',
  //     },
  //   ],
  //   required: false,
  //   group_key: 'PredictConfig',
  //   value_as_cmd: false,
  //   is_quick: false,
  //   is_estimator: true,
  //   readonly: true,
  //   dependencies: [
  //     {
  //       param_key: 'finetuning_type',
  //       values: ['lora'],
  //       op: 'eq',
  //       action: 'hidden',
  //     },
  //   ],
  // },
  {
    param_key: 'quantization_method',
    en_name: 'Quantization Method',
    zh_name: '量化方法',
    data_type: 'enum',
    default_value: 'bnb',
    description: '指定用于量化的算法，支持 “bnb”, “hqq” 和 “eetq”',
    enum_options: [
      {
        name: 'bnb',
        value: 'bnb',
      },
      {
        name: 'hqq',
        value: 'hqq',
      },
      {
        name: 'etqq',
        value: 'etqq',
      },
    ],
    required: false,
    group_key: 'PredictConfig',
    value_as_cmd: false,
    is_quick: false,
    is_estimator: true,
    readonly: true,
    dependencies: [
      {
        param_key: 'finetuning_type',
        values: ['lora'],
        op: 'eq',
        action: 'hidden',
      },
    ],
  },
  {
    param_key: 'template',
    en_name: 'Chat Template',
    zh_name: '对话模板',
    data_type: 'enum',
    default_value: 'qwen3',
    description: '训练和推理时构造 prompt 的模板',
    required: false,
    group_key: 'PredictConfig',
    value_as_cmd: false,
    is_quick: false,
    is_estimator: false,
    readonly: true,
    dependencies: [
      {
        param_key: 'finetuning_type',
        values: ['lora'],
        op: 'eq',
        action: 'hidden',
      },
    ],
  },
  {
    param_key: 'rope_scaling',
    en_name: 'RoPE Scaling',
    zh_name: 'RoPE插值',
    data_type: 'enum',
    enum_options: [
      {
        name: 'none',
        value: 'none',
      },
      {
        name: 'linear',
        value: 'linear',
      },
      {
        name: 'dynamic',
        value: 'dynamic',
      },
      {
        name: 'yarn',
        value: 'yarn',
      },
      {
        name: 'llama3',
        value: 'llama3',
      },
    ],
    default_value: 'none',
    description: 'RoPE Embedding 的缩放策略，支持 linear、dynamic、yarn 或 llama3。',
    required: false,
    group_key: 'PredictConfig',
    value_as_cmd: false,
    is_quick: false,
    is_estimator: true,
    dependencies: [
      {
        param_key: 'finetuning_type',
        values: ['lora'],
        op: 'eq',
        action: 'hidden',
      },
    ],
  },
  {
    param_key: 'booster',
    en_name: 'Compute Accelerate',
    zh_name: '计算加速',
    data_type: 'enum',
    enum_options: [
      {
        name: 'auto',
        value: 'auto',
      },
      {
        name: 'flashattn2',
        value: 'flashattn2',
      },
      {
        name: 'unsloth',
        value: 'unsloth',
      },
      {
        name: 'liger_kernel',
        value: 'liger_kernel',
      },
    ],
    default_value: 'liger_kernel',
    description: '评估时使用的提升器类型',
    required: false,
    group_key: 'PredictConfig',
    value_as_cmd: false,
    is_quick: false,
    is_estimator: true,
    dependencies: [
      {
        param_key: 'finetuning_type',
        values: ['lora'],
        op: 'eq',
        action: 'hidden',
      },
    ],
  },

  {
    param_key: 'eval_num_beams',
    en_name: 'Beam Search Number',
    zh_name: '束搜索数量',
    data_type: 'int',
    default_value: undefined,
    description: '模型评估时的 num_beams 参数',
    required: false,
    group_key: 'PredictConfig',
    value_as_cmd: false,
    is_quick: false,
    is_estimator: false,
    dependencies: [
      {
        param_key: 'finetuning_type',
        values: ['lora'],
        op: 'eq',
        action: 'hidden',
      },
    ],
  },

  {
    param_key: 'enable_thinking',
    en_name: 'Enable_thinking',
    zh_name: '深度思考',
    data_type: 'boolean',
    default_value: true,
    description: '启用深度思考',
    required: false,
    group_key: 'PredictConfig',
    value_as_cmd: false,
    is_quick: false,
    is_estimator: false,
  },

  // {
  //   param_key: 'global_batch_size',
  //   en_name: 'Global Batch Size',
  //   zh_name: '',
  //   data_type: 'int',
  //   default_value: 'per_device_train_batch_size * gradient_accumulation_steps * num_gpus',
  //   description: '全局批处理大小',
  //   required: true,
  //   group_key: 'TrainingConfig',
  //   value_as_cmd: false,
  //   is_quick: false,
  //   is_estimator: true,
  //   readonly: true
  // },
] as const;
